import { Exercise } from '@app/domain/routines/model/exercise.model';

/** Catalogo base de ejercicios. Sin imagenes: la UI usa iniciales del nombre. */
export const SEED_EXERCISES: readonly Exercise[] = [
  {
    id: 'ex-001',
    name: 'Sentadilla con barra',
    muscleGroup: 'legs',
    equipment: 'Barra',
    thumbnailUrl: null,
    instructions: [
      'Apoya la barra sobre los trapecios, no sobre el cuello.',
      'Separa los pies al ancho de los hombros, con las puntas levemente hacia afuera.',
      'Baja llevando la cadera atrás hasta que los muslos queden paralelos al suelo.',
      'Sube empujando con los talones, sin redondear la espalda.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-002',
    name: 'Peso muerto rumano',
    muscleGroup: 'legs',
    equipment: 'Barra',
    thumbnailUrl: null,
    instructions: [
      'Sujeta la barra con las manos al ancho de los hombros.',
      'Mantén las rodillas apenas flectadas durante todo el movimiento.',
      'Baja la barra pegada a las piernas llevando la cadera hacia atrás.',
      'Sube contrayendo glúteos al final del recorrido.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-003',
    name: 'Prensa de piernas',
    muscleGroup: 'legs',
    equipment: 'Máquina',
    thumbnailUrl: null,
    instructions: [
      'Apoya la espalda completa en el respaldo.',
      'Coloca los pies al ancho de la cadera en la plataforma.',
      'Baja controlando hasta formar 90 grados en la rodilla.',
      'Empuja sin bloquear la rodilla al final.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-004',
    name: 'Press banca',
    muscleGroup: 'chest',
    equipment: 'Barra',
    thumbnailUrl: null,
    instructions: [
      'Acuéstate con los omóplatos juntos y los pies firmes en el suelo.',
      'Toma la barra algo más ancho que los hombros.',
      'Baja la barra a la altura del pecho, con los codos a 45 grados.',
      'Empuja hasta extender los brazos sin bloquear el codo.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-005',
    name: 'Press inclinado con mancuernas',
    muscleGroup: 'chest',
    equipment: 'Mancuernas',
    thumbnailUrl: null,
    instructions: [
      'Ajusta el banco entre 30 y 45 grados.',
      'Sube las mancuernas a la altura del pecho.',
      'Empuja hacia arriba juntando levemente al final.',
      'Baja controlando durante dos segundos.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-006',
    name: 'Aperturas con mancuernas',
    muscleGroup: 'chest',
    equipment: 'Mancuernas',
    thumbnailUrl: null,
    instructions: [
      'Acuéstate en banco plano con las mancuernas sobre el pecho.',
      'Abre los brazos en arco con los codos levemente flectados.',
      'Baja hasta sentir estiramiento, sin forzar el hombro.',
      'Cierra contrayendo el pecho.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-007',
    name: 'Dominadas asistidas',
    muscleGroup: 'back',
    equipment: 'Máquina',
    thumbnailUrl: null,
    instructions: [
      'Toma la barra con agarre prono más ancho que los hombros.',
      'Baja los omóplatos antes de traccionar.',
      'Sube hasta que el mentón pase la barra.',
      'Baja controlando hasta extender los brazos.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-008',
    name: 'Remo con barra',
    muscleGroup: 'back',
    equipment: 'Barra',
    thumbnailUrl: null,
    instructions: [
      'Inclina el torso unos 45 grados con la espalda recta.',
      'Tracciona la barra hacia el abdomen bajo.',
      'Junta los omóplatos al final del movimiento.',
      'Baja controlando sin mover el torso.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-009',
    name: 'Jalón al pecho',
    muscleGroup: 'back',
    equipment: 'Polea',
    thumbnailUrl: null,
    instructions: [
      'Ajusta el rodillo sobre los muslos.',
      'Toma la barra ancho y saca pecho.',
      'Tira hacia la clavícula llevando los codos abajo y atrás.',
      'Sube controlando sin encoger los hombros.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-010',
    name: 'Press militar',
    muscleGroup: 'shoulders',
    equipment: 'Barra',
    thumbnailUrl: null,
    instructions: [
      'De pie, con la barra a la altura de la clavícula.',
      'Aprieta glúteos y abdomen para no arquear la espalda.',
      'Empuja la barra sobre la cabeza.',
      'Baja controlando hasta la clavícula.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-011',
    name: 'Elevaciones laterales',
    muscleGroup: 'shoulders',
    equipment: 'Mancuernas',
    thumbnailUrl: null,
    instructions: [
      'De pie con una mancuerna en cada mano.',
      'Sube los brazos hasta la altura del hombro.',
      'Mantén el codo levemente flectado.',
      'Baja lento, sin impulso.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-012',
    name: 'Curl de bíceps',
    muscleGroup: 'arms',
    equipment: 'Mancuernas',
    thumbnailUrl: null,
    instructions: [
      'De pie con los codos pegados al torso.',
      'Sube la mancuerna girando la palma hacia arriba.',
      'Contrae arriba sin mover el codo.',
      'Baja controlando hasta extender.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-013',
    name: 'Extensión de tríceps en polea',
    muscleGroup: 'arms',
    equipment: 'Polea',
    thumbnailUrl: null,
    instructions: [
      'Toma la cuerda con los codos pegados al cuerpo.',
      'Extiende los brazos hacia abajo separando la cuerda.',
      'Contrae el tríceps al final.',
      'Sube controlando sin despegar los codos.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-014',
    name: 'Plancha frontal',
    muscleGroup: 'core',
    equipment: null,
    thumbnailUrl: null,
    instructions: [
      'Apoya antebrazos y puntas de los pies.',
      'Alinea cabeza, cadera y talones.',
      'Aprieta abdomen y glúteos.',
      'Respira sin dejar caer la cadera.',
    ],
    ownerTrainerId: null,
  },
  {
    id: 'ex-015',
    name: 'Trote continuo',
    muscleGroup: 'cardio',
    equipment: 'Trotadora',
    thumbnailUrl: null,
    instructions: [
      'Comienza con dos minutos de caminata rápida.',
      'Sube a un ritmo en que puedas hablar con dificultad.',
      'Mantén el ritmo durante el tiempo indicado.',
      'Baja el ritmo dos minutos antes de terminar.',
    ],
    ownerTrainerId: null,
  },
];
