import { Routine } from '@app/domain/routines/model/routine.model';

/**
 * Rutina activa de Alejandra: cuatro dias (lunes, martes, jueves, viernes).
 * Los `exerciseId` referencian el catalogo de `exercises.seed.ts`.
 */
export const SEED_ROUTINES: readonly Routine[] = [
  {
    id: 'rtn-001',
    studentId: 'std-001',
    trainerId: 'trn-001',
    name: 'Hipertrofia — Bloque 2',
    goal: 'Ganar masa muscular y mejorar postura',
    startDate: '2026-09-01T00:00:00.000Z',
    endDate: '2026-11-30T00:00:00.000Z',
    status: 'active',
    days: [
      {
        id: 'day-001',
        weekday: 1,
        title: 'Tren inferior',
        focus: 'legs',
        estimatedMinutes: 55,
        exercises: [
          {
            id: 'rex-001',
            exerciseId: 'ex-001',
            name: 'Sentadilla con barra',
            order: 1,
            sets: 4,
            reps: 8,
            restSeconds: 90,
            weightKg: 40,
            notes: 'Sube la carga si las últimas dos salen limpias.',
          },
          {
            id: 'rex-002',
            exerciseId: 'ex-002',
            name: 'Peso muerto rumano',
            order: 2,
            sets: 3,
            reps: 10,
            restSeconds: 90,
            weightKg: 35,
            notes: null,
          },
          {
            id: 'rex-003',
            exerciseId: 'ex-003',
            name: 'Prensa de piernas',
            order: 3,
            sets: 3,
            reps: 12,
            restSeconds: 60,
            weightKg: 80,
            notes: null,
          },
          {
            id: 'rex-004',
            exerciseId: 'ex-014',
            name: 'Plancha frontal',
            order: 4,
            sets: 3,
            reps: 45,
            restSeconds: 45,
            weightKg: null,
            notes: 'Reps en segundos.',
          },
        ],
      },
      {
        id: 'day-002',
        weekday: 2,
        title: 'Empuje',
        focus: 'chest',
        estimatedMinutes: 50,
        exercises: [
          {
            id: 'rex-005',
            exerciseId: 'ex-004',
            name: 'Press banca',
            order: 1,
            sets: 4,
            reps: 8,
            restSeconds: 90,
            weightKg: 30,
            notes: null,
          },
          {
            id: 'rex-006',
            exerciseId: 'ex-005',
            name: 'Press inclinado con mancuernas',
            order: 2,
            sets: 3,
            reps: 10,
            restSeconds: 75,
            weightKg: 10,
            notes: null,
          },
          {
            id: 'rex-007',
            exerciseId: 'ex-010',
            name: 'Press militar',
            order: 3,
            sets: 3,
            reps: 10,
            restSeconds: 75,
            weightKg: 20,
            notes: null,
          },
          {
            id: 'rex-008',
            exerciseId: 'ex-013',
            name: 'Extensión de tríceps en polea',
            order: 4,
            sets: 3,
            reps: 12,
            restSeconds: 45,
            weightKg: 15,
            notes: null,
          },
        ],
      },
      {
        id: 'day-003',
        weekday: 4,
        title: 'Tracción',
        focus: 'back',
        estimatedMinutes: 50,
        exercises: [
          {
            id: 'rex-009',
            exerciseId: 'ex-007',
            name: 'Dominadas asistidas',
            order: 1,
            sets: 4,
            reps: 8,
            restSeconds: 90,
            weightKg: null,
            notes: 'Baja la asistencia cuando saques 10 limpias.',
          },
          {
            id: 'rex-010',
            exerciseId: 'ex-008',
            name: 'Remo con barra',
            order: 2,
            sets: 4,
            reps: 10,
            restSeconds: 75,
            weightKg: 25,
            notes: null,
          },
          {
            id: 'rex-011',
            exerciseId: 'ex-009',
            name: 'Jalón al pecho',
            order: 3,
            sets: 3,
            reps: 12,
            restSeconds: 60,
            weightKg: 30,
            notes: null,
          },
          {
            id: 'rex-012',
            exerciseId: 'ex-012',
            name: 'Curl de bíceps',
            order: 4,
            sets: 3,
            reps: 12,
            restSeconds: 45,
            weightKg: 8,
            notes: null,
          },
        ],
      },
      {
        id: 'day-004',
        weekday: 5,
        title: 'Full body y cardio',
        focus: 'fullbody',
        estimatedMinutes: 45,
        exercises: [
          {
            id: 'rex-013',
            exerciseId: 'ex-001',
            name: 'Sentadilla con barra',
            order: 1,
            sets: 3,
            reps: 12,
            restSeconds: 60,
            weightKg: 30,
            notes: 'Carga liviana, foco en técnica.',
          },
          {
            id: 'rex-014',
            exerciseId: 'ex-011',
            name: 'Elevaciones laterales',
            order: 2,
            sets: 3,
            reps: 15,
            restSeconds: 45,
            weightKg: 5,
            notes: null,
          },
          {
            id: 'rex-015',
            exerciseId: 'ex-006',
            name: 'Aperturas con mancuernas',
            order: 3,
            sets: 3,
            reps: 12,
            restSeconds: 45,
            weightKg: 7,
            notes: null,
          },
          {
            id: 'rex-016',
            exerciseId: 'ex-015',
            name: 'Trote continuo',
            order: 4,
            sets: 1,
            reps: 15,
            restSeconds: 0,
            weightKg: null,
            notes: 'Reps en minutos.',
          },
        ],
      },
    ],
  },
];
